#! /bin/bash -x
#
# copy-any-rootfs-inc [--incremental]
#
#    --incremental	if not specified: create new incremental series and
#			a first full backup
#			if specified: create next increment in the last
#			incremental series
#
# Environment variables that control backup:
#
#    SITE		mandatory: host name to back up
#    MAILTO		optional: list of addresses to send report to
#    SSH		optional: command to log into the host
#    BACKUP_DIRS:	optional: list of directories to back up
#

cd ~/backups/${SITE}-rootfs
TAIL=`date +%F-%T`
MAILTO=${MAILTO:-"jcmvbkbc@gmail.com kirill.krinkin@gmail.com"}
SSH=${SSH:-"ssh jcmvbkbc@${SITE}"}

if [ $# -gt 0 -a "$1" = "--incremental" ] ; then
    incremental=1
    SERIES=$(find -maxdepth 1 -name "series*" -type d | sort | tail -n 1)
else
    incremental=0
    SERIES=series-${TAIL}
fi

for (( i=0 ; i < 4; i++ ))
do
    ${SSH} "uptime ; echo ; df -h ; echo" > headline
    ${SSH} "echo ; top -b -n 1" > bottomline
    if [ $incremental = 1 ] ; then
        gzip -3 < ${SERIES}/filelist | ${SSH} "zcat | sudo tee /tmp/filelist > /dev/null"
    else
        mkdir ${SERIES}
        ${SSH} "sudo rm -f /tmp/filelist"
    fi
    ${SSH} "sudo tar -c --one-file-system --listed-incremental=/tmp/filelist -C / ${BACKUP_DIRS:-.} | nice gzip -3" > ${SERIES}/${SITE}-${TAIL}.tgz 2>log-${TAIL}
    [ -f ${SERIES}/filelist ] && mv ${SERIES}/filelist{,.old}
    ${SSH} "sudo cat /tmp/filelist | gzip -3" | zcat > ${SERIES}/filelist
    ${SSH} "cd /tmp ; sudo md5sum filelist" > ${SERIES}/filelist.md5sum

    if cat ${SERIES}/${SITE}-${TAIL}.tgz | tar -tz >fl-new 2>err && ( cd ${SERIES} ; md5sum -c filelist.md5sum ) 2>err
    then
        if [ $incremental = 1 ] ; then
            grep -v ".*/$" fl-new > fl-diff
            echo "Changed (increment): $(cat fl-diff | wc -l)" >> headline
        else
            diff -bu fl fl-new > fl-diff
            echo "Changed (since last full dump): $(grep '^[+-][^+-]' fl-diff | wc -l)" >> headline
            mv fl-new fl
        fi
        cat headline fl-diff bottomline | mail -s "${SITE} backup diff" ${MAILTO}
        break
    else
        if [ $incremental = 1 ] ; then
            mv ${SERIES}/filelist{.old,}
            rm -f ${SERIES}/${SITE}-${TAIL}.tgz
        else
            rm -rf ${SERIES}
        fi
        cat headline bottomline err | mail -s "${SITE} backup failed" ${MAILTO}
    fi

    sleep 900

done

find -maxdepth 1 -name "series*" -type d | sort | head -n -2 | xargs rm -rf
find -maxdepth 1 -name 'log*' -type f | sort | head -n -14 | xargs rm -f
